name: Deploy Laravel to CPanel via FTP

on:
  push:
    branches:
      - main  # Thực hiện khi có push vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Kiểm tra mã nguồn của bạn từ GitHub

    - name: Set up PHP
      uses: shivammathur/setup-php@v2  # Cài đặt PHP
      with:
        php-version: '7.4'  # Chọn phiên bản PHP mà bạn đang sử dụng
        tools: 'composer'

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache  # Caches Composer dependencies
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php  # Cài đặt Composer nếu chưa có
        php composer.phar install --no-dev --optimize-autoloader  # Cài đặt các phụ thuộc của Laravel

    - name: Build environment file
      run: |
        cp .env.example .env  # Sao chép file .env.example thành .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env
        echo "AWS_BUCKET=${{ secrets.AWS_BUCKET }}" >> .env
        echo "AWS_URL=${{ secrets.AWS_URL }}" >> .env

    - name: Deploy to CPanel via FTP
      uses: appleboy/ftp-action@v1.1.2  # Sử dụng FTP action của appleboy
      with:
        host: ${{ secrets.SERVER }}  # Địa chỉ FTP server (ví dụ: ftp.yourdomain.com)
        username: ${{ secrets.USERNAME }}  # Tên người dùng FTP
        password: ${{ secrets.PASSWORD }}  # Mật khẩu FTP
        port: 21  # Cổng FTP mặc định (21)
        source: "./"  # Thư mục nguồn (thư mục hiện tại)
        target: "/ntu257.vpsttt.vn/git"  # Thư mục đích trên cPanel (ví dụ: /public_html)
