name: Deploy Laravel to CPanel via FTP

on:
  push:
    branches:
      - main  # Trigger deployment when there's a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout code from your GitHub repository

    - name: Set up PHP
      uses: shivammathur/setup-php@v2  # Set up PHP
      with:
        php-version: '7.4'  # Specify the PHP version you're using

    - name: Deploy to CPanel via FTP (easypanel/ftp-deploy-action)
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.SERVER }}  
        username: ${{ secrets.USERNAME }} 
        password: ${{ secrets.PASSWORD }}  
        local-dir: "./" 
        server-dir: "/ntu257.vpsttt.vn/git/"  
