name: Deploy Laravel to CPanel

on:
  push:
    branches:
      - main  # Thực hiện khi có push vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Kiểm tra mã nguồn của bạn từ GitHub

    - name: Set up PHP
      uses: shivammathur/setup-php@v2  # Cài đặt PHP
      with:
        php-version: '7.4'  # Chọn phiên bản PHP mà bạn đang sử dụng
        tools: 'composer'

    - name: Install dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php  # Cài đặt Composer
        php composer.phar install --no-dev --optimize-autoloader  # Cài đặt các phụ thuộc của Laravel

    - name: Build environment file
      run: |
        cp .env.example .env  
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env
        echo "AWS_BUCKET=${{ secrets.AWS_BUCKET }}" >> .env
        echo "AWS_URL=${{ secrets.AWS_URL }}" >> .env

    - name: Deploy to CPanel via SSH
      uses: appleboy/ssh-action@v0.1.1 
      with:
        server: ${{ secrets.SERVER }} 
        username: ${{ secrets.USERNAME }}  # Tên người dùng CPanel
        password: ${{ secrets.PASSWORD }}  # Mật khẩu CPanel
        port: 21 
